export const INTERNAL_ERROR_CODES = {
  SERVER_ERROR: "SERVER_ERROR",
  CLIENT_ERROR: "CLIENT_ERROR",
  XML_PARSE_ERROR: "XML_PARSE_ERROR",
  INVALID_XML: "INVALID_XML",
  INVALID_RESPONSE: "INVALID_RESPONSE",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  TRANSPORT_ERROR: "TRANSPORT_ERROR",
} as const;

export type InternalErrorCode = (typeof INTERNAL_ERROR_CODES)[keyof typeof INTERNAL_ERROR_CODES];
